### ISSUE TITLE
Correlation Problems in Matlab2021b

### ISSUE THREAD

**Issue by sasasuta** [ICAMS/Kanapy#21]
After running: 

> kanapy setupTexture

 I encountered some problems:
`Is MATLAB installed in this system (yes/no): yes
Searching your system for MATLAB ...
Found MATLAB in /home/shen/polyspace/R2021b/bin/matlab, continue (yes/no): yes
Error using quit
Unrecognized function or variable 'Settings'.
 
Error using quit
Unrecognized function or variable 'Settings'.
 
/home/shen/.conda/envs/knpy/lib/python3.8/site-packages/setuptools/dist.py:519: InformationOnly: Normalizing '2021b.0' to '2021b0'
  self.metadata.version = self._normalize_version(
/home/shen/.conda/envs/knpy/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/shen/.conda/envs/knpy/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer, pypa/build or
        other standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/shen/.conda/envs/knpy/lib/python3.8/site-packages/setuptools/command/sdist.py:119: SetuptoolsDeprecationWarning: `build_py` command does not inherit from setuptools' `build_py`.
!!

        ********************************************************************************
        Custom 'build_py' does not implement 'get_data_files_without_manifest'.
        Please extend command classes from setuptools instead of distutils.

        See https://peps.python.org/pep-0632/ for details.
        ********************************************************************************

!!
  self._add_data_files(self._safe_data_files(build_py))
zip_safe flag not set; analyzing archive contents...
matlab.__pycache__.__init__.cpython-38: module references __file__
matlab.__pycache__.__init__.cpython-38: module references __path__
matlab.engine.__pycache__.__init__.cpython-38: module references __file__
Unrecognized function or variable 'startup'.

Traceback (most recent call last):
  File "init_engine.py", line 11, in <module>
    eng.startup(nargout=0)
  File "/home/shen/.conda/envs/knpy/lib/python3.8/site-packages/matlabengineforpython-2021b0-py3.8.egg/matlab/engine/matlabengine.py", line 70, in __call__
    return FutureResult(self._engine(), future, nargs, _stdout,
  File "/home/shen/.conda/envs/knpy/lib/python3.8/site-packages/matlabengineforpython-2021b0-py3.8.egg/matlab/engine/futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "/home/shen/.conda/envs/knpy/lib/python3.8/site-packages/matlabengineforpython-2021b0-py3.8.egg/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: Unrecognized function or variable 'startup'.
`

**Comment by AHartmaier** [comment]
Installation procedure for Matlab Engine API for Python has been updated to support current Matlab versions.

**Comment by sasasuta** [comment]
test of texture still failed

**Comment by sasasuta** [comment]
when i try matlab R2017b and run "kanapy setupTexture", some errors occur:

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/shen/MATLAB/R2017b/extern/engines/python/setup.py", line 13, in <module>
          raise EnvironmentError('MATLAB Engine for Python supports Python version'
      OSError: MATLAB Engine for Python supports Python version 2.7, 3.4, 3.5 and 3.6 but your version of Python is 3.8
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "init_engine.py", line 9, in <module>
    import matlab.engine
ModuleNotFoundError: No module named 'matlab'
