### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by JDeroy** [ICAMS/Kanapy#23]
Following previously closed issue (Software installation issue #9) I also encountered installation issue whilst following the installation guide. I verified that I have both g++ and cmake installed.

![image](https://github.com/ICAMS/Kanapy/assets/145694384/04ad0fe8-94b5-4d6a-8dac-bf1f65df0ef1)

I even tried to manually cmake (using command: cmake -S .. -B. -G "MinGW Makefiles"):
![image](https://github.com/ICAMS/Kanapy/assets/145694384/f180efe0-df32-4190-8b6d-90cc63e83c14)

Then I tried to make the file but got errors from pybind11:
![image](https://github.com/ICAMS/Kanapy/assets/145694384/c75b9a6f-bfa2-47a7-a88f-2e9b8fe9981d)

There might be some compatibility issues with new versions libraries (I'm no expert) as in the "libs" folder of the build using that method, I don't have the eigen being copied.

Also the version that is being installed seems to be kanapy 4.0.1 when i use the command pip install kanapy@git+https://github.com/ICAMS/Kanapy

Is there something I missed as I never had that much trouble installing a python module.

Thank you in advance for your help.

**Comment by JDeroy** [comment]
Also I forgot to mention, I tried installing that on Windows 11. I'm going to try and install an older version to see what may be working.

**Comment by AHartmaier** [comment]
The new version of kanapy is a pure python version and doesn't require any C++ compiling. Please check if this version works on your Windows system.

**Comment by JDeroy** [comment]
Hi! The new version works perfectly well and passes the runTests on Windows. Thank you very much for your quick reply! I will then close this issue.
