### ISSUE TITLE
How to identify the phase of a grain in 2 phase microstructure

### ISSUE THREAD

**Issue by hem-28** [ICAMS/Kanapy#7]
Hello,

Not quite an issue, but I didn't find a discussion board, hence posting it here.
I used the 2 phase packing example and was able to generate the microstructure. In the abaqus output, it created element sets for each grain. But how do I identify which phase the grain belongs to? What kind of function do I have to user? 
Also, would it be possible to export a VTK RECTILINEAR GRID which could be visualized in ParaView? 

Thanks!

**Comment by GolsaTolooeiEshlaghi** [comment]
Hello,

Thanks for your comment.

Now it is possible to use knpy.writeAbaqusPhase(ms.RVE_data['Grains']) function to write the phases to a material file for abaqus.
